version: "3"
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
  app:
    build:
      context: .
    container_name: app
    ports:
      - 9080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docker
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SERVER_PORT=8080
    depends_on:
      - db

volumes:
  db_data:
